import { Order } from "../types/order";

export const combinedData: Order[] = [
  {
    id: 1,
    amount: 23500,
    quantity: 101,
    date: "10 May 2024",
    shop: "Palm Meadows, Prestige Ozone, Bengaluru",
    pickUp: "Hosur Road ChikkuLakshmia layout",
    delivery: "Tanisandra main road",
    rejectedBy: "Antony",
    assignee: "Antony",
  },
  {
    id: 2,
    amount: 43500,
    quantity: 500,
    date: "10 May 2024",
    shop: "Prestige Eureka, Church Street, Bengaluru",
    pickUp: "Mantri Mall, Sampige Rd",
    delivery: "24, Vittal Mallya Rd Bengaluru",
    rejectedBy: "Ben",
    assignee: "Ben",
  },
  {
    id: 3,
    amount: 55200,
    quantity: 150,
    date: "20 May 2024",
    shop: "12th Main Rd, Indiranagar, Bengaluru",
    pickUp: "Hosur Rd, Chikku Lakshmaiah Layout",
    delivery: "Thanisandra Main Rd, Bengaluru",
    rejectedBy: "John",
    assignee: "John",
  },
  {
    id: 4,
    amount: 55200,
    quantity: 150,
    date: "20 May 2024",
    shop: "12th Main Rd, Indiranagar, Bengaluru",
    pickUp: "Hosur Rd, Chikku Lakshmaiah Layout",
    delivery: "Thanisandra Main Rd, Bengaluru",
    rejectedBy: "John",
    assignee: "John",
  },
  {
    id: 5,
    amount: 55200,
    quantity: 150,
    date: "20 May 2024",
    shop: "12th Main Rd, Indiranagar, Bengaluru",
    pickUp: "Hosur Rd, Chikku Lakshmaiah Layout",
    delivery: "Thanisandra Main Rd, Bengaluru",
    rejectedBy: "John",
    assignee: "John",
  },
  {
    id: 6,
    amount: 55200,
    quantity: 150,
    date: "20 May 2024",
    shop: "12th Main Rd, Indiranagar, Bengaluru",
    pickUp: "Hosur Rd, Chikku Lakshmaiah Layout",
    delivery: "Thanisandra Main Rd, Bengaluru",
    rejectedBy: "John",
    assignee: "John",
  },
  {
    id: 7,
    amount: 55200,
    quantity: 150,
    date: "20 May 2024",
    shop: "12th Main Rd, Indiranagar, Bengaluru",
    pickUp: "Hosur Rd, Chikku Lakshmaiah Layout",
    delivery: "Thanisandra Main Rd, Bengaluru",
    rejectedBy: "John",
    assignee: "John",
  },
];


